name: Build and Deploy Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Decode Keystore
      env:
          ENCODED_STRING: ${{ secrets.KEYSTORE_FILE }}
      run: |
          TMP_KEYSTORE_FILE_PATH=~/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/assistant_keystore.jks
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
      
    - name: Install Flutter
      uses: subosito/flutter-action@v1
      
    - name: Build Android App Bundle
      run: flutter build appbundle --release --target-platform android-arm,android-arm64,android-x64
      
    - name: Sign App Bundle
      run: jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore ~/keystore/assistant_keystore.jk -storepass ${{ secrets.KEYSTORE_PASSWORD }} ./build/app/outputs/bundle/release/app.aab ${{ secrets.KEY_ALIAS }}
      
    - name: Verify Signed App Bundle
      run: jarsigner -verify -verbose -certs ./build/app/outputs/bundle/release/app.aab
      
    - name: Upload App Bundle to Play Console
      uses: r0adkll/upload-google-play@v1
      with:
        service_account_json: ${{ secrets.GOOGLE_PLAY_CONSOLE_JSON }}
        package_name: com.juliuscanute.learningassistant
        track: internal
        release_status: completed
        app_files: ./build/app/outputs/bundle/release/app.aab
