name: Build and Deploy Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Decode Keystore
      id: decode_keystore
      uses: timheuer/base64-to-file@v1
      with:
        fileName: 'assistant_keystore.jks'
        fileDir: './keystore/'
        encodedString: ${{ secrets.KEYSTORE_FILE }}
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adopt'
      
    - name: Install Flutter
      uses: subosito/flutter-action@v1
      
    - name: Build Android App Bundle
      run: flutter build appbundle --release

    - name: Sign App Bundle
      run: jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore keystore/assistant_keystore.jks -storepass ${{ secrets.KEYSTORE_PASSWORD }} ./build/app/outputs/bundle/release/app-release.aab ${{ secrets.KEY_ALIAS }}

    - name: Verify Signed App Bundle
      run: jarsigner -verify -verbose -certs ./build/app/outputs/bundle/release/app-release.aab     
      
    - name: Upload App Bundle to Play Console
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_CONSOLE_JSON }}
        packageName: com.juliuscanute.learningassistant
        track: internal
        status: completed
        releaseFiles: ./build/app/outputs/bundle/release/app-release.aab
