name: Build and Deploy Windows App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MS Store Developer CLI
      uses: microsoft/setup-msstore-cli@v1
  
    # - name: Configure MS Store credentials
    #   run: msstore reconfigure --tenantId ${{ secrets.AZURE_AD_TENANT_ID }} --clientId ${{ secrets.AZURE_AD_CLIENT_ID }} --clientSecret ${{ secrets.AZURE_AD_CLIENT_SECRET }} --sellerId ${{ secrets.MS_STORE_SELLER_ID }}

    - name: Install Flutter
      uses: subosito/flutter-action@v1

    - name: Download pub dependencies
      run: flutter pub get

    - name: Build via Flutter
      run: flutter build windows --release

    - name: Upload build to workflow run
      uses: actions/upload-artifact@v1
      with:
        name: LittleLight-windows
        path: ${{ github.workspace }}/build/windows/x64/runner/Release
  
    - name: Create release zip
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: "zip"
        filename: "LearningAssistant-windows.zip"
        path: ${{ github.workspace }}/build/windows/x64/runner/Release

    - name: Upload build to Github Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.run_number }}
        files: "LittleLight-windows.zip"

    # - name: Create MSIX package
    #   run: msstore package

    # - name: Publish MSIX to the Microsoft Store
    #   run: msstore publish -v -i ./build/windows/x64/runner/Release